### ISSUE TITLE
Exception thrown: 'OpenTK.Graphics.GraphicsContextException' in OpenTK.dll An unhandled exception of type 'OpenTK.Graphics.GraphicsContextException' occurred in OpenTK.dll Requested GraphicsMode not available. SetPixelFormat error: 2000

### ISSUE THREAD

**Issue by TheWhirlingWhiteWizard** [Metric/Materia#2]
Hello, when I try to build this using Visual Studio I get the following Error:

Exception thrown: 'OpenTK.Graphics.GraphicsContextException' in OpenTK.dll
An unhandled exception of type 'OpenTK.Graphics.GraphicsContextException' occurred in OpenTK.dll
Requested GraphicsMode not available. SetPixelFormat error: 2000

Is this the result of an incorrectly referenced OpenTK, and if so, how do I fix this?

**Comment by CarstenZarbock** [comment]
in InitGL() change the GraphicsMode to

`glview = new TK.GLControl(GraphicsMode.Default);`

**Comment by TheWhirlingWhiteWizard** [comment]
Thank You, This was the solution.
