### ISSUE TITLE
Crash if you try to move children windows

### ISSUE THREAD

**Issue by CarstenZarbock** [Metric/Materia#4]
> Exception thrown: 'System.InvalidOperationException' in mscorlib.dll
> An unhandled exception of type 'System.InvalidOperationException' occurred in mscorlib.dll
> Null object needs a value

OnChildrenCollectionChanged() (DockWidth is null)

**Comment by Metric** [comment]
Hmm, will look into this when I get a chance. Which window were you trying to drag, or was it any of the windows?

**Comment by Metric** [comment]
Fixed in latest git push. It appears, I missed some null checks for DockWidth and DockHeight when I converted them to a nullable reference.
