### ISSUE TITLE
Compilation troubles

### ISSUE THREAD

**Issue by The-Lerix** [Metric/Materia#6]
Hello,
I've got several troubles with compilation (actually I don't really know how to do it)
Could it be possible to get an .exe file? Your software seems very interesting to me.
Thanks!

**Comment by Metric** [comment]
Hi, sorry for the delay in getting back to this, but I was working on improvements and various bug fixes over the last few days. 

I have posted a pre-alpha 0.0.1 to: https://github.com/Metric/Materia/releases/download/0.0.1/materia.prealpha.0.0.1.zip

You can find it under releases for now.
